### ISSUE TITLE
Add react router

### ISSUE THREAD

**Issue by BrtSkr** [FilipRedlich/coop-shop#2]

**Comment by ASANIYAN** [comment]
Can I get a more explicit explanation?

Would love to work on this.

**Comment by BrtSkr** [comment]
Hi! To give better explanation of this issue: We need to add routes to this application, to be honest code might be quite messy and complicated because we were trying new things and to make it work on dev you would have to change every variable for ex. products to productsTest. If you're interested or need help you can hit me up on Discord since I reply there more often.
Arcadam88#4721

**Comment by ASANIYAN** [comment]
Alright. I'll send you a message in discord soonest.

**Comment by ASANIYAN** [comment]
I've sent a request to you on discord - AyomidePaul#1392
